application: bmhsign
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: helloworld.application
- url: /authpage
  script: auth.app
- url: /auth
  script: auth.app
- url: /do/.*
  script: do.app
- url: /localtest/.*
  script: localtest.app
- url: /cron/.*
  script: cronjob.app
